(TeX-add-style-hook "background"
 (lambda ()
    (LaTeX-add-bibitems
     "wikifinitedifferences"
     "Heath"
     "wikimaxprinciple"
     "BC"
     "Diener"
     "Olsson1"
     "Olsson1Sup"
     "Olsson2")
    (LaTeX-add-labels
     "eq:1d:wave"
     "eq:domains"
     "eq:initial:boundary:data"
     "eq:r:s:def"
     "eq:wave:transformed:1"
     "eq:wave:transformed:2"
     "eq:boundary:conditions:r:s"
     "eq:derivative:operator"
     "eq:integration:by:parts"
     "eq:inner:product"
     "eq:discrete:inner:product"
     "eq:summation:by:parts:proof:1"
     "eq:summation:by:parts:proof:2")
    (TeX-add-symbols
     "R"
     "eval")
    (TeX-run-style-hooks
     "hyperref"
     "listings"
     "braket"
     "verbatim"
     "mathrsfs"
     "graphicx"
     "latexsym"
     "amssymb"
     "amsmath"
     "fullpage"
     "latex2e"
     "art10"
     "article")))

